language: node_js
node_js:
- '8'
- '10'
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: tUTw7XrogBvc58pn2kRaraPaO1L7ruhQTIzIrG/Thxmdb5DJnenU2s1gy56BD9+DMz+2dXBS0Di3UlHcRCdl2a6i1qk21ju8FhdRSxQVwn/WmEg/j2dqzvh6gngutpfEjATQFfP8qua24ancyixAGfrT/9tPTQlZyoL6606+EZTBNZZ3C/9abTPAda8Kn9De+nOcVr+NGpUeVIPDgRpFzPJJq/lbR8Egminj5apMlGbyjzCjskEu2PUJcFGYIsPkTMqhhbGY5csJxxnvJ1SjKV5253lOaGSfzsgy3SKEszS5sT7YgR0qy7jVmFnBJwrNGfYUef4DsU62trTTRwEUm2S9vO5ruMiZwFsRJAz1To+ua76zD7kzdafozBp2YYFPdH8d0CZ5IXlc58lhkv5J+AujE0Nw9vLCPRysIUcnYb8/gaDsKCe/SVbqLeebp9Y3S4PU8G82P3LP4o/Zj7sEKf6izse2A2xgcW1jUNnjlwHgd9a9tj2oZ+DN9kdRyi8eewd2QjKmGnR1fgyj+FEjUJzEphU4ylzRZKARq2fBGA6hflKGfaFs8I8xCpb8TyowSP2U3/Glb+EWOj8HcUb2EmfPgiVgScUVkMGdccfuKx22VQOz2AchA3k0seFF2gF4EolFtB7+DDkDpN14QfwsphNRC+QP5JOgXRewzgFFcE0=
  on:
    tags: true
    repo: breadhead/use-modal
